// Sample tile data to populate game board - temporary

export default [
    {tile: [0, 0], data: {type: 'sheep', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [0, 1], data: {type: 'ore', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [0, 2], data: {type: 'wheat', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [1, 0], data: {type: 'sheep', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [1, 1], data: {type: 'brick', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [1, 2], data: {type: 'ore', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [1, 3], data: {type: 'wood', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [2, 0], data: {type: 'brick', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [2, 1], data: {type: 'wheat', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [2, 2], data: {type: 'sheep', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [2, 3], data: {type: 'sheep', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [2, 4], data: {type: 'ore', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [3, 0], data: {type: 'sheep', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [3, 1], data: {type: 'wood', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [3, 2], data: {type: 'wood', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [3, 3], data: {type: 'wheat', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [3, 4], data: {type: 'brick', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [3, 5], data: {type: 'sheep', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [4, 0], data: {type: 'ore', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [4, 1], data: {type: 'wheat', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [4, 2], data: {type: 'sheep', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [4, 3], data: {type: 'wood', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [4, 4], data: {type: 'sheep', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [5, 0], data: {type: 'ore', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [5, 1], data: {type: 'sheep', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [5, 2], data: {type: 'wheat', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [5, 3], data: {type: 'brick', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [6, 0], data: {type: 'ore', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [6, 1], data: {type: 'wood', rollVal: Math.ceil(Math.random() * 12)}},
    {tile: [6, 2], data: {type: 'sheep', rollVal: Math.ceil(Math.random() * 12)}}
]
